# Generated by Django 4.2.16 on 2024-10-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='name',
        ),
    ]
