# Generated by Django 4.2.16 on 2024-10-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_author_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='author',
        ),
    ]
